# action.yml
name: 'demo-jdbc'
description: 'A demo to pick numbers from euromillions...'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - clean_final_output_winners.txt
    - clean_final_output_star.txt
- name: Discord notification
  env:
      DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1026788478094159872/1EYUqwFrv4qLktmyPTZqnPcncem8DKjNdiSkqwdioDekwSv6PohJjbCZOzYuvOeExj0k"
  uses: Ilshidur/action-discord@master
  with:
      args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
